# Generated by Django 5.0.7 on 2025-04-24 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du groupe')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la cotisation')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('ouverte', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_cree_par', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='sexe', max_length=2, null=True)),
                ('code', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Code')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nationalité')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de téléphone')),
                ('profession', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_cree_par', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_supprime_par', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CotisationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('date_cotisation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la cotisation')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant payé')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cotisation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_item_cree_par', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membre', verbose_name='Membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('date_presence', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la présence')),
                ('presence', models.CharField(max_length=30)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_cree_par', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membre', verbose_name='Membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SousGroupe',
            fields=[
                ('groupe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.groupe')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_sous_groupe', to='app.groupe')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.groupe', models.Model),
        ),
        migrations.AddField(
            model_name='membre',
            name='sous_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
