# Generated by Django 5.0.7 on 2025-04-24 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('motif', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
