# Generated by Django 5.0.7 on 2025-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom du groupe'),
        ),
    ]
