# Generated by Django 5.0.7 on 2025-04-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_groupe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
