# Generated by Django 5.0.7 on 2025-04-27 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_membre_sous_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groupe', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sousgroupe', to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
