# Generated by Django 5.0.7 on 2025-04-27 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_membre_email_membre_modifie_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('date_presence', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la présence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(choices=[('présent', 'Présent'), ('absent', 'Absent'), ('permissionnaire', 'Permissionnaire')], max_length=30),
        ),
        migrations.AddField(
            model_name='presence',
            name='liste_presence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.listpresence', verbose_name='Liste de présence'),
            preserve_default=False,
        ),
    ]
