# Generated by Django 5.0.7 on 2025-04-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_listpresence_alter_presence_presence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpresence',
            name='groupe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.groupe'),
            preserve_default=False,
        ),
    ]
