# Generated by Django 5.0.7 on 2025-04-29 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_listpresence_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(choices=[('présent', 'Présent'), ('absent', 'Absent'), ('permissionnaire', 'Permissionnaire'), ('retard', 'Retard')], max_length=30),
        ),
        migrations.CreateModel(
            name='Promesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('date_promesse', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_echéance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type_promesse', models.CharField(blank=True, choices=[('Espèce', 'Espèce'), ('Nature', 'Nature')], default='Espèce', max_length=20, null=True)),
                ('unite', models.CharField(blank=True, default='Francs CFA', max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membre', verbose_name='Membre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
