# Generated by Django 5.0.7 on 2025-04-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_presence_presence_promesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promesse',
            old_name='date_echéance',
            new_name='date_echeance',
        ),
    ]
