# Generated by Django 5.0.7 on 2025-04-29 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_date_echéance_promesse_date_echeance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promesse',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promesse_cree_par', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='promesse',
            name='date_echeance',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'échéance"),
        ),
    ]
