# Generated by Django 5.0.7 on 2025-04-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_promesse_cree_par_alter_promesse_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='groupe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.groupe'),
            preserve_default=False,
        ),
    ]
