# Generated by Django 5.0.7 on 2025-04-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_depense_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sousgroupe', to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
