# Generated by Django 5.0.7 on 2025-04-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_membre_sous_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='numero',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
