# Generated by Django 5.0.7 on 2025-04-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_membre_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depensesousgroupe', to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
