# Generated by Django 5.0.7 on 2025-11-07 19:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_depense_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Membre.photo_upload, verbose_name='Photo'),
        ),
    ]
