# Generated by Django 5.0.7 on 2025-11-08 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_membre_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpresence',
            name='nom',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='listpresence',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_presence_sous_groupe', to='app.sousgroupe'),
        ),
    ]
