# Generated by Django 5.0.7 on 2025-04-26 08:31

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_deleted_at_user_groupe_user_numero_user_poste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profl',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.User.nom_photo_profil, verbose_name='Photo de profil'),
        ),
    ]
