# Generated by Django 5.0.7 on 2025-04-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_membre_email_membre_modifie_par'),
        ('auth_app', '0005_user_photo_profl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sous_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sous_groupe', to='app.sousgroupe', verbose_name='Sous groupe'),
        ),
    ]
