# Generated by Django 5.0.7 on 2025-05-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=250, verbose_name='Nom et Prénoms')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('objet', models.CharField(max_length=150, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
