# Generated by Django 5.0.7 on 2025-10-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='prenom',
            field=models.CharField(default='prenom', max_length=250, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='Nom'),
        ),
    ]
